### PR TITLE
Added Fully Responsive Navbar

### PR DESCRIPTION
**Pull request by minhaj-313**
Added Fully Responsive Navbar

### CODE REVIEW

**Comment by phyleria** [comment]
Hi @minhaj-313 thank you for your contribution.
Kindly go through the [website design](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=220%3A129&t=t2V9vY4no4pVNiEd-0) to guide you on the coloring and specifications of the navbar.
Looking forward to the changes!

**Comment by Khadeeejah** [comment]
hi @minhaj-313 kindly do a pull or rebase to fix your conflicts

**Comment by minhaj-313** [comment]
> hi @minhaj-313 kindly do a pull or rebase to fix your conflicts

Yeah Now, it is done, I did resolve it.

**Review by Khadeeejah — APPROVED** [review]
Approved ready to merge

**Comment by minhaj-313** [comment]
@Khadeeejah Thank You

**Comment by Khadeeejah** [comment]
@minhaj-313  I have reverted your commit 
Please follow the design attached to the issue
Thank you

**Pull request merged**
