### PR TITLE
Feature/tab section

### LINKED ISSUE #54: Create Blog Event Videos Nav section

### PR DESCRIPTION
**Pull request by octocatblain**
- add tabs section
- add active tab JS

| Before fix: | After fix and feature add: |
|-------------|----------------------------|
| Screenshot from 2024-03-07 12-27-18 | Screenshot from 2024-03-07 12-26-44 |

closes #54 

@phyleria done!

### CODE REVIEW

**Review by phyleria — CHANGES_REQUESTED** [review]
Thanks for working on this @octocatblain 

Could you kindly make the paragraph centered on the page?

**Comment by octocatblain** [comment]
> Thanks for working on this @octocatblain
> 
> Could you kindly make the paragraph centered on the page?

Done ✔️

**Comment by phyleria** [comment]
Thanks @octocatblain 

Just a little update, the tab is ok at the center as it is now but can we have the descriptions running from end to end instead of at the center? I think that'll be all.

**Comment by octocatblain** [comment]
> Thanks @octocatblain
> 
> Just a little update, the tab is ok at the center as it is now but can we have the descriptions running from end to end instead of at the center? I think that'll be all.

**Fix**:
Screenshot from 2024-03-07 17-46-45

- I also added a media qury for mobile responsiveness

Screenshot from 2024-03-07 17-49-41

**Pull request merged**
