### PR TITLE
Feature/responsiveness

### LINKED ISSUE #5: [UI] Navbar Implementation
Implement the Navbar 

[Figma design](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=230%3A188&t=fMbtxmVcO2YETJ1i-4)

### LINKED ISSUE #55: Syntax Error in style.css file
There is an error in CSS file.

### LINKED ISSUE #66: Mobile responsiveness
- hero section 
- Navbar section
- Featured posts section

Kindly assign me this @phyleria @Khadeeejah

### PR DESCRIPTION
**Pull request by octocatblain**
- add mobile responsiveness to all sections
- make layout and alignment corrections to all sections
- make navbar fixed
- add site icon and meta description

- Closes #66 
- Closes #55 
- Closes #5 

| **Before** | **After** |
| ------ | ----- |
| Chimoney-Community-Website | Chimoney-Community-Website (1) |

| **Mobile View Before** | **Mobile View After** |
| ------------------ | ----------------- |
| iPhone-13-PRO-chimoney github io | iPhone-13-PRO-127 0 0 1 (1) |

**Menu after:**
iPhone-13-PRO-127 0 0 1 (2)

@phyleria Done ✅

### CODE REVIEW

**Comment by phyleria** [comment]
Hi @octocatblain 

Good work!

I noticed for the web changes; the before has different content from the after. The `after` isn't updated with the other changes you had made and now shows 6 featured blogs. Could you kindly update this?
Thanks.

**Comment by octocatblain** [comment]
> Hi @octocatblain
> 
> Good work!
> 
> I noticed for the web changes; the before has different content from the after. The `after` isn't updated with the other changes you had made and now shows 6 featured blogs. Could you kindly update this? Thanks.

@phyleria Done ☑️ 

- I added the missing tab section and corrected the footer.
- The replicated the extra blog posts because that's what shown on the [Figma File](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?type=design&node-id=220-129&mode=design&t=vO2yE9HaOzPeWrF3-0) &mdash; If you only need 3 posts showing you can comment out the extra posts from the [main.js](https://github.com/Chimoney/Community-Website/blob/master/assets/js/main.js) file before merging this branch.


**After:**

Chimoney-Community-Website (2)

**Comment by phyleria** [comment]
Hi @octocatblain 

Looks good on my end. Can you kindly resolve the file conflicts before I merge.

**Comment by octocatblain** [comment]
@phyleria Conflicts resolved 💯

**Review by phyleria — APPROVED** [review]
Thanks.

**Pull request merged**
