### PR TITLE
[feat]: Finalized the community care section

### LINKED ISSUE #10: [UI] implement "Community Care Section"
Implement the community care section

[Figma](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=233%3A688&t=fMbtxmVcO2YETJ1i-4)

### PR DESCRIPTION
**Pull request by grand-rick001**
closes #10 

Here's the solution: ![Community Care Section Image] @Khadeeejah @phyleria (https://res.cloudinary.com/dv765kdgq/image/upload/v1679273110/comm-care_o8gzp8.png)

### CODE REVIEW

**Comment by grand-rick001** [comment]
closes #10

**Comment by Khadeeejah** [comment]
Screenshot 2023-03-20 at 07 17 15
 hi please work on your font and aslso check the padding and margins

**Comment by grand-rick001** [comment]
On it

**Comment by grand-rick001** [comment]
Done, @Khadeeejah

**Comment by phyleria** [comment]
LGTM 🎉

**Review by phyleria — APPROVED** [review]
With a few changes to the margin, this is good to go!
Will go ahead and merge it

**Pull request merged**
